# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# platform :android do


# #   desc "Submit a new Beta Build to Crashlytics Beta"
# #   lane :beta do
# #     gradle(task: "clean assembleRelease")
# #     crashlytics
  
# #     # sh "your_script.sh"
# #     # You can also use other beta testing services here
# #   end

# #   desc "Deploy a new version to the Google Play"
# #   lane :deploy do
# #     gradle(task: "clean assembleRelease")
# #     upload_to_play_store
# #   end
# end

platform :android do
  before_all do
    ENV["JAVA_HOME"] = "/usr/lib/jvm/jdk1.8.0_261"
  end

  desc "Clean"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Build debug"
  lane :build do
    gradle(task: "assembleDebug")
  end

  desc "Runs all debug tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Runs integration tests debug"
  lane :integration do
    automated_test_emulator_run(
      AVD_setup_path: "./fastlane/AVD_configs/AVD_config.json",
      gradle_task: "connectedDebugAndroidTest",
      AVD_param_launch_timeout: "600",
      AVD_recreate_new: false,
      AVD_clean_after: false,
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
